
version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts/packages/*.nupkg
test: off
deploy: off